---
title: "3-exp2-pilot"
output: html_document
date: "2026-02-24"
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
source(file = "./utils/exp2-utils.R") # loads all necessary packages
```

## Preparing the data
```{r data load}
dataPath <- "data/exp2/"
mg_pilot_df <- read_csv(paste(dataPath, "pilot-mg-raw.csv", sep = ""), show_col_types = FALSE)
us_pilot_df <- read_csv(paste(dataPath, "pilot-us-raw.csv", sep = ""), show_col_types = FALSE)
```

```{r filter out partial data}
# Keep only data w/ percentComplete 100% i.e. only ppt who finished the study
manual_keep_ids <- c("09b12105-8844-4979-b829-450cea06e9ee")
mg_pilot_df_finished <- mg_pilot_df %>%
  getPercentComplete() %>%
  group_by(participantId) %>%
  filter(
    (any(!is.na(percentComplete)) &&
      max(percentComplete, na.rm = TRUE) == 100
    ) || any(participantId %in% manual_keep_ids)) %>% ungroup()

us_pilot_df_finished <- us_pilot_df %>%
  getPercentComplete() %>%
  group_by(participantId) %>%
  filter(any(!is.na(percentComplete)) &&
    max(percentComplete, na.rm = TRUE) == 100) %>% ungroup()
```

```{r filter out ppt who failed at least two ishihara tests and failed at least one attention checks}
mg_ishihara_fail_ids <- get_ishihara_fail_ids(mg_pilot_df_finished, fail_threshold = 2)
us_ishihara_fail_ids <- get_ishihara_fail_ids(us_pilot_df_finished, fail_threshold = 2)

mg_attention_fail_ids <- get_attention_fail_ids(mg_pilot_df_finished, fail_threshold = 1, normalize_keys = TRUE,  trial_pattern = "^attention_")
us_attention_fail_ids <- get_attention_fail_ids(us_pilot_df_finished, fail_threshold = 1, normalize_keys = FALSE, trial_pattern = "^attention_")

mg_exclude_ids <- union(mg_ishihara_fail_ids, mg_attention_fail_ids)
us_exclude_ids <- union(us_ishihara_fail_ids, us_attention_fail_ids)

mg_pilot_df_pass_all <- mg_pilot_df_finished %>%
  filter(!participantId %in% mg_exclude_ids)
us_pilot_df_pass_all <- us_pilot_df_finished %>%
  filter(!participantId %in% us_exclude_ids)
```

From here, working only with the data from ppt who:
- completed the study > passed ishihara test > passed at least two attention checks

```{r generate demographic data}
mg_pilot_dem <- getDemographics(mg_pilot_df_pass_all)
us_pilot_dem <- getDemographics(us_pilot_df_pass_all)
```

```{r get cleaner - parsed response data}
# ID, Concept A, Concept B, Answer, Response Time, Category(MG_US_level), Color_left, Color_right, left_height, right_height
mg_ppt_response_df <- mg_pilot_df_pass_all %>%
  filter(responseId == "choice",
    str_detect(trialId, "^p[^_]*_s[^_]*_t[^_]*$")) %>%
  select(participantId, trialId, answer)

mg_clean_df <- getCleanData(mg_ppt_response_df) %>% 
  rename(conA_fr = conA, conB_fr = conB)
# Translate concept vector: French -> English
fr_to_en <- setNames(conceptListEn, conceptListFr)
mg_clean_df <- mg_clean_df %>%
  mutate(conA = fr_to_en[conA_fr], conB = fr_to_en[conB_fr], 
         .after = 'conA_fr') # %>% select(-c(conA_fr, conB_fr))

us_ppt_response_df <- us_pilot_df_pass_all %>%
  filter(responseId == "choice",
    str_detect(trialId, "^p[^_]*_s[^_]*_t[^_]*$")) %>%
  select(participantId, trialId, answer)
us_clean_df <- getCleanData(us_ppt_response_df)
```

```{r save data}
# write.csv(mg_clean_df, "data/exp2/pilot-mg-df.csv", row.names = FALSE, fileEncoding = "UTF-8")
# write.csv(mg_pilot_dem, "data/exp2/pilot-mg-dem.csv", row.names = FALSE, fileEncoding = "UTF-8")
# 
# write.csv(us_clean_df, "data/exp2/pilot-us-df.csv", row.names = FALSE, fileEncoding = "UTF-8")
# write.csv(us_pilot_dem, "data/exp2/pilot-us-dem.csv", row.names = FALSE, fileEncoding = "UTF-8")
```

## Analysing data

```{r data load}
dataPath <- "data/exp2/"
mg_df <- read_csv(paste(dataPath, "pilot-mg-df.csv", sep = ""), show_col_types = FALSE)
mg_dem <- read_csv(paste(dataPath, "pilot-mg-dem.csv", sep = ""), show_col_types = FALSE)

us_df <- read_csv(paste(dataPath, "pilot-us-df.csv", sep = ""), show_col_types = FALSE)
us_dem <- read_csv(paste(dataPath, "pilot-us-dem.csv", sep = ""), show_col_types = FALSE)

stimuli <- read_csv(paste(dataPath, "exp2-stimuli.csv", sep = ""), show_col_types = FALSE)
```


```{r merge pilot data to stimuli}
# us_df_with_answer <- us_df %>%
#   left_join(
#     stimuli %>%
#       select(conA, conB, col1, col2, x1_us, x2_us, x3_us, x4_us, p_gt0_us, dX_us, dS_us, dS_diff) %>%
#       distinct(conA, conB, .keep_all = TRUE),by = c("conA", "conB"))
# 
# us_df_acc2 <- us_df_with_answer %>%
#   mutate(
#     accuracy = case_when(
#       dX_us > 0 &
#         col1 == conA_col_ans &
#         col2 == conB_col_ans ~ 1,
# 
#       dX_us < 0 &
#         col1 == conB_col_ans &
#         col2 == conA_col_ans ~ 1,
# 
#       TRUE ~ 0
#     )); rm(us_df_with_answer)

mg_df_with_answer <- addStimuliInfo(mg_df, stimuli, "_mg") %>% select(-c(conA_fr, conB_fr))
mg_df_acc <- addAccuracy(mg_df_with_answer); rm(mg_df_with_answer)
mg_df_acc$group = "mg"

us_df_with_answer <- addStimuliInfo(us_df, stimuli, "_us")
us_df_acc <- addAccuracy(us_df_with_answer); rm(us_df_with_answer)
us_df_acc$group = "us"
```

```{r haha}
# US dataset
us_ <- us_df %>% filter(mgLevel == "MG_LOW", usLevel == "US_LOW") 
summary()
```



