---
title: "color-exp1"
# author: "nr"
date: "2023-12-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source(file = './utils/utils.R')  # loads all necessary packages
source(file = './utils/stimuli.R')
```

### Data loading and prep
```{r}
en_debug <- read_csv("data/exp1/csv/en-20231214-debug.csv") %>% rename(code = color)
en_debrief <- read_csv("data/exp1/csv/en-20231214-debrief.csv") %>% select(ID, expCountry)
en_debug <- left_join(en_debug, en_debrief, by = "ID")

en_mdg = filter(en_debug, grepl("mdg", expCountry)); en_mdg$expCountry <- 'mdg'
en_usa = filter(en_debug, !grepl("mdg", expCountry)); en_usa$expCountry <- 'usa'
en_debug = rbind(en_mdg, en_usa)

df <- en_debug %>% select(concept, code, answer, expCountry)
# df$answer[df$answer < 0 ] <- 0
df$rating <- round(df$answer/100, digits = 2)
df_weights <- df %>% group_by(expCountry, concept, code) %>% summarize(
  weight = round(mean(rating), digits = 2),
  se = round(sd(rating)/sqrt(length(rating)), digits = 2)
)

# adding hex color values to en_debug
df_weights <- full_join(df_weights, bcp37, by = "code")
```

```{ barplot default (code names ordered alphabetically)}
df_weights %>% 
  filter(concept %in% c("angry", "banana")) %>%
  ggplot(aes(x = reorder(code, weight), y = weight, fill = code)) +
  geom_bar(stat = 'identity', color = "black") +
  scale_fill_manual(values = df_weights$hex) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1))+
  facet_grid(rows = vars(concept)) + 
  # facet_wrap(~concept, ncol = 1, scales = 'free_x') + 
  labs(title = "mean color-concept association ratings", x = "color code in the BCP-37 library", ) +
  theme_bw()
```

```{r using tidytext - bars ordered by weight ratings}
# df_weights$code = factor(df_weights$code, levels = color_codes, ordered = TRUE) 
plot <- df_weights %>%
  filter(concept %in% c("carrot","justice", "comfort")) %>%
ggplot(aes(x = reorder_within(code, weight, concept), y = weight, fill = code)) + 
    geom_bar(stat = 'identity', color = 'black', width = 0.75) + 
    scale_x_reordered() +
    scale_fill_manual(values = df_weights$hex) + 
    # scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
    facet_wrap(~concept, scales = "free_x", ncol = 1, strip.position = 'right') +
    labs(title = "mean color-concept association ratings (5 participants - color library: BCP-37)", x = "color code in the BCP-37 library", ) +
    theme_bw() +
    theme(legend.position = "none"); plot
```

```{r using tidytext - bars ordered by color codes + error bars}
# error bars are +/- standard errors of the means: se = sd(rating/sqrt(length(rating)))

df_weights$code = fct_rev(factor(df_weights$code, levels = color_codes))
plot <- df_weights %>%
  # filter(concept %in% c("carrot","justice")) %>%
ggplot(aes(x = code, y = weight, fill = hex)) + 
    geom_bar(stat = 'identity', color = 'black',size = 0.15,width = 0.985) + 
    geom_errorbar( aes(x=code, ymin=weight-se, ymax=weight+se), width=0.4, colour="black", alpha=0.6, size=0.25)+
    scale_fill_identity()+ 
    scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
    # facet_wrap(~concept+expCountry, scales = "free_x", ncol = 2, strip.position = 'right') +
    # facet_grid(rows = vars(concept))+
    facet_grid(concept ~ expCountry)+
    labs(title = "mean color-concept assoc. ratings (14 participants 7/7 - library: BCP-37)", x = "", ) +
    theme_bw() +
    theme(legend.position = "none", strip.text = element_text(size = 12)); plot
```

```{r}
ggsave(file="./fig/20231214-weights-err-bars.png", plot = plot, width=10, height=16)
```

