---
title: "exp1-data-prep 2026"
output: html_document
date: "2025-12-17"
---

This file contains the preparation for the datasets to be analyzed for ``us`` and ``mg`` participants

usdem = us demography data; usdf = us trial data
mgdem = mg demography data; mgdf = mg trial data

```{r}
source(file = './utils/exp1-utils.R')  # loads all necessary packages //NOTE: some packages
source(file = './utils/stimuli.R')
```

Note: 
- ``rating`` is the ans/100
- ``weight`` is the average rating across all participants for each {color, concept} pair

```{r MG demography}
mgdem1 <- read.csv("data/exp1/csv/clean/mg-dem-p1.csv", encoding = "UTF-8")
mgdem2 <- read.csv("data/exp1/csv/clean/mg-dem-p2.csv", encoding = "UTF-8")
mgdem3 <- read.csv("data/exp1/csv/clean/mg-dem-p3.csv", encoding = "UTF-8")

mgdem123 <- rbind(mgdem1, mgdem2, mgdem3)

mgdem <- mgdem123 %>% filter(progressBlock == 14, progressColor == 37)
rm(mgdem1, mgdem2, mgdem3, mgdem123)

## fixing details
mgdem <- mgdem %>%
  rename(professionFr = profession) %>% 
  mutate(profession = professionFr, .after = professionFr) %>%
  mutate(profession = replace(profession, profession %in% c("musicien"), "musician")) %>%
  mutate(profession = replace(profession, profession %in% c("chauffeur"), "driver")) 

# replace job names in FR to EN. Inspired by the function translateConcepts
jobFr = c("musicien", "infographiste", "secretaire", "medecin", "chauffeur")
jobEn = c("musician", "infographist", "secretary", "physician", "driver")
mgdem$profession <- replace(mgdem$professionFr, 
                        mgdem$professionFr %in% jobFr, 
                        jobEn[match(mgdem$professionFr[mgdem$professionFr %in% jobFr], jobFr)])
rm(jobFr, jobEn)
```

```{r MG data}
mgdf1 <- read.csv("data/exp1/csv/clean/mg-p1.csv", encoding = "UTF-8")
mgdf2 <- read.csv("data/exp1/csv/clean/mg-p2.csv", encoding = "UTF-8")
mgdf3 <- read.csv("data/exp1/csv/clean/mg-p3.csv", encoding = "UTF-8")

mgdf123 <- rbind(mgdf1, mgdf2, mgdf3)

mgdf <- mgdf123 %>% filter(ID %in% unique(mgdem$sessionID))
mgdf <- translateConcepts(mgdf, conceptListFr3, conceptListEn3)
mgdf$expCountry = "mdg"
mgdf$rating = round(mgdf$ans/100, digits = 3)

rm(mgdf1, mgdf2, mgdf3, mgdf123)
```

```{r US demography}
usdem1 <- read.csv("data/exp1/csv/clean/us-dem-p1.csv", encoding = "UTF-8")
usdem2 <- read.csv("data/exp1/csv/clean/us-dem-p2.csv", encoding = "UTF-8")
usdem3 <- read.csv("data/exp1/csv/clean/us-dem-p3.csv", encoding = "UTF-8")
usdem3alt <- read.csv("data/exp1/csv/clean/us-dem-p3-alt.csv", encoding = "UTF-8")

usdem123 <- rbind(usdem1, usdem2, usdem3, usdem3alt)

usdem <- usdem123 %>% filter(progressBlock == 14, progressColor == 37)
usdem <- usdem %>% mutate(gender = replace(gender, gender %in% c("m"), "male"))

rm(usdem1, usdem2, usdem3, usdem3alt, usdem123)
```

```{r US data}
usdf1 <- read.csv("data/exp1/csv/clean/us-p1.csv", encoding = "UTF-8")
usdf2 <- read.csv("data/exp1/csv/clean/us-p2.csv", encoding = "UTF-8")
usdf3 <- read.csv("data/exp1/csv/clean/us-p3.csv", encoding = "UTF-8")
usdf3alt <- read.csv("data/exp1/csv/clean/us-p3-alt.csv", encoding = "UTF-8")

usdf123 <- rbind(usdf1, usdf2, usdf3, usdf3alt)
usdf <- usdf123 %>% filter(ID %in% unique(usdem$sessionID))

usdf$expCountry <- 'usa'
usdf$rating <- round(usdf$ans/100, digits = 3)

rm(usdf1, usdf2, usdf3, usdf3alt, usdf123)
```

```{r write data}
write_csv(usdem, "data/exp1/csv/2026/us-dem.csv")
write_csv(usdf, "data/exp1/csv/2026/us-df.csv")

write_csv(mgdem, "data/exp1/csv/2026/mg-dem.csv")
write_csv(mgdf, "data/exp1/csv/2026/mg-df.csv")
```

## Computing weights and SE
```{r}
mgdf_w <- mgdf %>% group_by(concept, color) %>% 
  summarize(weight = round(mean(rating), digits = 4),
            se = round(sd(rating)/sqrt(length(rating)), digits = 4), .groups = 'drop') # standard error
mgdf_w <- full_join(mgdf_w, bcp37hex, by = "color") %>% mutate(barStroke = ifelse(color == "WH", "#000000", hex)) # barStroke is the color of the stroke of the bar when plotting. Stroke is black for white bars
mgdf_w$expCountry = "mdg"
#####

usdf_w <- usdf %>% group_by(concept, color) %>% 
  summarize(weight = round(mean(rating), digits = 4),
            se = round(sd(rating)/sqrt(length(rating)), digits = 4), .groups = 'drop') # standard error
usdf_w <- full_join(usdf_w, bcp37hex, by = "color") %>% mutate(barStroke = ifelse(color == "WH", "#000000", hex)) 
usdf_w$expCountry = 'usa'
```

```{r write data with weights}
write_csv(usdf_w, "data/exp1/csv/2026/us-df-weight.csv")
write_csv(mgdf_w, "data/exp1/csv/2026/mg-df-weight.csv")
```



