---
title: "exp1-p3"
output: html_document
date: "2024-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file = './utils/exp1-utils.R')  # loads all necessary packages 
source(file = './utils/stimuli.R')
```

# Malagasy dataset
### Analysis of scaled data collection
n = 50

```{r data-prep-p3-mg}
mgdem <- read_csv("data/exp1/csv/clean/mg-dem-p3.csv") %>% filter(progressBlock == 14, progressColor == 37)
mgdf <- read_csv("data/exp1/csv/clean/mg-p3.csv") %>% filter(ID %in% unique(mgdem$sessionID)) 

conceptListEn3 = c('banana', 'mango', 'peach', 'death', 'justice', 'peace', 'safety',
               'angry', 'happy', 'sad', 'sick', 'lightning', 'sandstorm', 'tree')
conceptListFr3 = c('banane', 'mangue', 'pêche', 'mort', 'justice', 'peace', 'sécurité',
               'en colère', 'heureux', 'triste', 'malade', 'foudre', 'tempête de sable', 'arbre')
mgdf <- translateConcepts(mgdf, conceptListFr3, conceptListEn3)
mgdf$expCountry <- "mdg"

# adding weights
mgdf$rating <- round(mgdf$ans/100, digits = 3)

mgdf_w <- mgdf %>% group_by(expCountry, concept, color) %>% summarize(
    weight = round(mean(rating), digits = 3),
    se = round(sd(rating)/sqrt(length(rating)), digits = 3), .groups = 'drop') # standard error
mgdf_w <- full_join(mgdf_w, bcp37hex, by = "color") %>% mutate(barStroke = ifelse(color == "WH", "#000000", hex))
```

```{r eval=FALSE}
write_csv(mgdf_w, "data/exp1/csv/clean/p3-mg-weight.csv")
```

```{r data-prep-p3-us}
usdem <- read_csv("data/exp1/csv/clean/us-dem-p3.csv") %>% filter(progressBlock == 14, progressColor == 37)
usdem_alt <- read_csv("data/exp1/csv/clean/us-dem-p3-alt.csv") %>% filter(progressBlock == 14, progressColor == 37)
usdem <- rbind(usdem, usdem_alt)

usdf <- read_csv("data/exp1/csv/clean/us-p3.csv") 
usdf_alt <- read_csv("data/exp1/csv/clean/us-p3-alt.csv") 
usdf <- rbind(usdf, usdf_alt) %>% filter(ID %in% unique(usdem$sessionID)) ; rm(usdem_alt, usdf_alt)
usdf$expCountry <- "usa"

# addign weights
usdf$rating <- round(usdf$ans/100, digits = 3)
usdf_w <- usdf %>% group_by(expCountry, concept, color) %>%  summarise(
    weight = round(mean(rating), digits = 3), 
    se = round(sd(rating)/sqrt(length(rating)), digits = 3), .groups = 'drop')
usdf_w <- full_join(usdf_w, bcp37hex, by = 'color') %>% mutate(barStroke = ifelse(color == 'WH', "#000000", hex))
```
```{r}
write_csv(usdf_w, "data/exp1/csv/clean/p3-us-weight.csv")
```

### Analyzing within group
```{r plot weight-mg}
mgdf_w$con = factor(mgdf_w$concept, levels=conceptListEn3) # to order the facet strips 
p1 <- mgdf_w %>% 
  # filter(concept %in% c("mango", "tree", "angry", "happy", "death")) %>%
  ggplot(aes(reorder_within(color, weight, concept), weight, fill = hex, color = barStroke)) + 
  geom_bar(stat = 'identity',size = 0.15, width = 0.80) + 
  geom_errorbar( aes(x=reorder_within(color, weight, concept), ymin=weight-se, ymax=weight+se), width=0.4, colour="black", alpha=0.6, size=0.25)+
  scale_fill_identity() + scale_color_identity() +
  scale_x_reordered() +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
  facet_wrap(~ con, scales = "free_x", ncol = 1) +
  labs(x = "", title = "Mean weight of associations, library: BCP37, MDG") + 
  theme_light() +
  theme(legend.position = "none",
        strip.text = element_text(size = 12, color = "black"), 
        strip.background = element_blank()); p1
```

```{r eval=FALSE}
ggsave(file="./fig/p3-weight-mg.png", plot = p1, width=10, height=16)
```


##### Dump
```{r DELETEME}
a <- filter(mgdf, expCountry == "mdg", concept == "angry", color == "BK") 
mean(a$rating)
round(sd(a$rating)/sqrt(length(a$rating)), digits = 2)
```

