---
title: "exp1-pilot study #2"
output: html_document
date: "2024-02-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file = './utils/exp1-utils.R')  # loads all necessary packages //NOTE: some packages
source(file = './utils/stimuli.R')
```

#### Analysis of pilot #2
```{r data-prep2}
usa_dem <- read_csv("data/exp1/csv/p2-usa-dem.csv") %>% 
  filter(expCountry == "usa2") %>% 
  filter(progressBlock == 16, progressColor == 37)
usa_dem$country <- "usa"
usa <- read_csv("data/exp1/csv/p2-usa.csv") %>% filter(ID %in% unique(usa_dem$sessionID))
usa$country <- "usa"

mdg_dem <- read_csv("data/exp1/csv/p2-mdg-dem.csv") %>% filter(expCountry == "mdg2") %>%
  filter(progressBlock == 16, progressColor == 37)
mdg_dem$country <- "mdg"
mdg <- read_csv("data/exp1/csv/p2-mdg.csv") %>% filter(ID %in% unique(mdg_dem$sessionID)) %>%
  rename(conceptFr = concept) 
mdg$conceptFr <- tolower(mdg$conceptFr)
mdg$concept <- conceptListEn2[match(mdg$conceptFr, conceptListFr2)] # replacing the concepts values of conceptListFr2 in mdg$conceptFr with their respective matches in conceptListEn2
mdg$conceptFr <- NULL; 
mdg$country <- "mdg"

df <- rbind(mdg, usa)
df$rating <- round(df$ans/100, digits = 2)
```

```{r}
df_w <- df %>% group_by(country, concept, color) %>% summarize(
  weight = round(mean(rating), digits = 2),
  se = round(sd(rating)/sqrt(length(rating)), digits = 2)) # standard error
df_w <- full_join(df_w, bcp37hex, by = "color")
```

### Concepts' weights and ratings
##### Mean color-concept association ratings for 16 concepts.

```{r}
df_w$color = fct_rev(factor(df_w$color, levels = color_codes))
plot <- df_w %>%
ggplot(aes(x = color, y = weight, fill = hex)) +
# ggplot(aes(x = reorder(color, weight), y = weight, fill = hex)) + 
    geom_bar(stat = 'identity', color = 'black',size = 0.15, width = 0.985) + 
    geom_errorbar( aes(x=color, ymin=weight-se, ymax=weight+se), width=0.4, colour="black", alpha=0.6, size=0.25)+
    scale_fill_identity()+ 
    scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
    facet_grid(factor(concept, levels=sort(conceptListEn2)) ~ country)+
    labs(title = "Pilot 2: mean color-concept assoc. ratings (10 part. - library: BCP-37)", x = "", ) +
    theme_bw() +
    theme(legend.position = "none", strip.text = element_text(size = 12)); plot
```


```{r TEST}

```

```{r eval=FALSE}
ggsave(file="./fig/p2-weight.png", plot = plot, width=10, height=16)
```

Comparing the differences between the means (t-test at conf.level = 0.95)
```{r echo=FALSE}
r <- ci_t.test(df, conceptListEn2, "only p2 data"); r
```

```{r eval=FALSE}
ggsave(file="./fig/p2-ci-diff.png", plot = r, width=8, height=14)
```

### Analysing the combination for all datasets  (READ COMMENTS)
```{r}
# getting the data from before p1
# run line 20:30 from exp1-p0 then
df0 <- df %>% rename(country = expCountry, ans = answer)

# getting the data from before p2
# run line 16:21 then 29:36 in exp1-p1 then
df1 <- rbind(usdf, mgdf) %>% rename(country = expCountry) %>% 
  select(concept, color, ans, country, rating)

# run 'data-prep2' chunk in this file
<< data-prep2 >>
df2 <- df %>% select(concept, color, ans, country, rating)

# merge all data and keep only overlapping concepts
dfAll <- rbind(df0, df1, df2)
```

##### with all concepts
```{r}
ci_t.test(dfAll, union(conceptListEn1, conceptListEn2), "all concepts")
```

##### with overlapping concepts
```{r}
dfAll_ <- dfAll %>% filter(concept %in% intersect(unique(df0$concept), unique(df2$concept)) )
s <- ci_t.test(dfAll_, conceptListEn2, "only overlapping concepts"); s
```

```{r eval=FALSE}
ggsave(file="./fig/p0p1p2-ci-diff.png", plot = s, width=8, height=14)
```