---
title: "exp1-p3"
output: html_document
date: "2024-07-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(file = './utils/exp1-utils.R')  # loads all necessary packages 
source(file = './utils/stimuli.R')
```

# Malagasy dataset
### Analysis of scaled data collection
n = 50

```{r data-prep-p3-mg}
# mgdem <- read_csv("data/exp1/csv/clean/mg-dem-p3.csv") %>% filter(progressBlock == 14, progressColor == 37)
# mgdf <- read_csv("data/exp1/csv/clean/mg-p3.csv") %>% filter(ID %in% unique(mgdem$sessionID)) 
# 
# conceptListEn3 = c('banana', 'mango', 'peach', 'death', 'justice', 'peace', 'safety',
#                'angry', 'happy', 'sad', 'sick', 'lightning', 'sandstorm', 'tree')
# conceptListFr3 = c('banane', 'mangue', 'pêche', 'mort', 'justice', 'peace', 'sécurité',
#                'en colère', 'heureux', 'triste', 'malade', 'foudre', 'tempête de sable', 'arbre')
# mgdf <- translateConcepts(mgdf, conceptListFr3, conceptListEn3)
# mgdf$expCountry <- "mdg"
# 
# # adding weights
# mgdf$rating <- round(mgdf$ans/100, digits = 3)
# 
# mgdf_w <- mgdf %>% group_by(expCountry, concept, color) %>% summarize(
#     weight = round(mean(rating), digits = 3),
#     se = round(sd(rating)/sqrt(length(rating)), digits = 3), .groups = 'drop') # standard error
# mgdf_w <- full_join(mgdf_w, bcp37hex, by = "color") %>% mutate(barStroke = ifelse(color == "WH", "#000000", hex))
```

```{r eval=FALSE}
# write_csv(mgdf, "data/exp1/csv/clean/p3-mg.csv")
# write_csv(mgdf_w, "data/exp1/csv/clean/p3-mg-weight.csv")
```


```{r data-prep-p3-us}
# -alt.csv data are named so because they are stored in a separate 'alternative' firebase database due to R/W limitation per project on firebase.  
# usdem <- read_csv("data/exp1/csv/clean/us-dem-p3.csv") %>% filter(progressBlock == 14, progressColor == 37)
# usdem_alt <- read_csv("data/exp1/csv/clean/us-dem-p3-alt.csv") %>% filter(progressBlock == 14, progressColor == 37)
# usdem <- rbind(usdem, usdem_alt)
# 
# usdf <- read_csv("data/exp1/csv/clean/us-p3.csv") 
# usdf_alt <- read_csv("data/exp1/csv/clean/us-p3-alt.csv") 
# usdf <- rbind(usdf, usdf_alt) %>% filter(ID %in% unique(usdem$sessionID)) ; rm(usdem_alt, usdf_alt)
# usdf$expCountry <- "usa"
# 
# # adding weights
# usdf$rating <- round(usdf$ans/100, digits = 3)
# usdf_w <- usdf %>% group_by(expCountry, concept, color) %>%  summarise(
#     weight = round(mean(rating), digits = 3), 
#     se = round(sd(rating)/sqrt(length(rating)), digits = 3), .groups = 'drop')
# usdf_w <- full_join(usdf_w, bcp37hex, by = 'color') %>% mutate(barStroke = ifelse(color == 'WH', "#000000", hex))
```

```{r}
# write_csv(usdf, "data/exp1/csv/clean/p3-us.csv")
# write_csv(usdf_w, "data/exp1/csv/clean/p3-us-weight.csv")
```

### Analyzing within group
```{r plot assoc. weights}
## Association weight MDG
mgdf_w$con = factor(mgdf_w$concept, levels=conceptListEn3) # to order the facet strips 
p1 <- plotWeight_Err(mgdf_w, "Mean weight of assoc, lib: BCP37, MDG"); p1
  
## Association weight USA
usdf_w$con = factor(usdf_w$concept, levels=conceptListEn3) # to order the facet strips 
p2 <- plotWeight_Err(usdf_w, "Mean weight of assoc., lib: BCP37, USA") + 
  theme(axis.title.y = element_blank(), axis.text.y = element_blank()); p2 

p12 <- grid.arrange(p1, p2, nrow = 1)
```

```{r eval=FALSE}
ggsave(file="./fig/p3-weight-mg.png", plot = p1, width=10, height=16)
ggsave(file="./fig/p3-weight-us.png", plot = p2, width=10, height=16)
ggsave(file="./fig/p3-weight-both.png", plot = p12, width=10, height=16)
```
